### ISSUE TITLE
Game window automatically minimise

### ISSUE THREAD

**Issue by TENSTORM777** [MadDeCoDeR/Classic-RBDOOM-3-BFG#155]
**Describe the bug**
When I got out the mouse capture, the game window automatically minimise.
**To Reproduce**
1. Launch the game
2. Set the windowed or borderless
3. Get out of the mouse capture(or alt+tab)
4. The window automatically minimise and can't move

**Desktop (please complete the following information):**
 - OS: Windows11
 - GPU AMD Radeon Graphics
 - Monitor 1920x1080 no HDR no Free/G sync HDMI
 - GPU Driver Version 32.0.11021.3002
 - Version [DOOM BFA Nigthly 2024-09-07-21-48-1725745727]

**Comment by MadDeCoDeR** [comment]
Hi, that's not a bug that is a feature. When the game loses focus it's minimizing itself and pauses in the process. That happens just in case something happened and the game is no longer in focus.
Except if I'm missing something here, usually on Windows you can have only one app in focus, which means that all your inputs should be focus on that one app. If DOOM BFA is not on focus then your input will no longer register to the game and that's why the game pauses

**Comment by TENSTORM777** [comment]
Then, how can I move or resize the window? 
Maybe I’m just missing something but the cursor gets locked within the game window, even in the menu, so I can't touch the edges of the window. I know I can specify the window position in the additional parameters, but I want to be able to move it while playing as well.
I'm sorry if the text is hard to read as I'm using a translation tool.

**Comment by MadDeCoDeR** [comment]
Oh, that. Just use Alt + Backspace to free the mouse. Note: For now it only works when the in game mouse is available. Which means that you can use it either in the main menu or when you pause DOOM 3

**Comment by TENSTORM777** [comment]
That worked! Thanks for the answer. Your work is amazing.
