### ISSUE TITLE
errormessage overflow when activating Quad Buffer in 3D settings

### ISSUE THREAD

**Issue by TheVoodoo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#5]
GL_CheckErrors(); in RenderSystem.cpp (Line 797) causes an errormessage overflow in console when activating Quad Buffer in 3D settings

**Comment by MadDeCoDeR** [comment]
I fail to replicate this issue. Can you give me your PC specs?

**Comment by TheVoodoo** [comment]
nv GTX1070/8G
i5-4670k
Win10

![screen](https://user-images.githubusercontent.com/16653359/45703717-6d0df880-bb75-11e8-94d6-0eee6b064a3e.jpg)

**Comment by TheVoodoo** [comment]
tbh i don't know what quad buffer or GL_CheckErrors(); is supposed to do (i'm no coder), but i'm using this trick to enable the laser sight that is restricted to the stereoscopic modes. :)

However, this infinite errormessage cycle i get when activating quad buffer, drops the framerate from 144 to 12. Disabling the line //GL_CheckErrors(); stops the errorflood (yeah i know, pretty clear logic) and the game runs fine with this setting, but i don't know which further impact it has to the game.

**Comment by MadDeCoDeR** [comment]
I found the Issue. On gl_backend.cpp search for glDrawBuffers(GL_BACK_RIGHT); and comment it out. So far I haven't noticed any HUGE issue (graphically or game breaking). I will upload the updated code once I release the new Version (which might take some time because I really want to release 1.1.11 but in order to do so I want to put more than one or two bugfixes/improvments).

**Comment by MadDeCoDeR** [comment]
This issue is now fixed on version 1.1.11-classic
